--- Makefile	2018-07-07 17:56:28.000000000 -0400
+++ Makefile_new	2018-07-01 17:13:41.072175000 -0400
@@ -59,14 +59,14 @@
 
 # install for development, using pinned dependencies, and including dev-only dependencies
 install:
-	-pip uninstall -y crossbar
-	pip install --no-cache --upgrade -r requirements-dev.txt
-	pip install -e .
+	-pip3 uninstall -y crossbar
+	pip3 install --no-cache --upgrade -r requirements-dev.txt
+	pip3 install -e .
 	@python -c "import crossbar; print('*** crossbar-{} ***'.format(crossbar.__version__))"
 
 # install using pinned/hashed dependencies, as we do for packaging
 install_pinned:
-	-pip uninstall -y crossbar
+	-pip3 uninstall -y crossbar
 	LMDB_FORCE_CFFI=1 SODIUM_INSTALL=bundled pip install --ignore-installed --require-hashes -r requirements.txt
 	pip install .
 	@python -c "import crossbar; print('*** crossbar-{} ***'.format(crossbar.__version__))"
